{% set name = "papermill" %}
{% set version = "0.19.0" %}
{% set sha256 = "d62d7edcb635040a84ccf42b6dcc7e9163a8945059c8eee5211218f56d8f3904" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - codecov
    - coverage
    - notebook
    - mock
    - pytest>=4.1
    - pytest-cov>=2.6.1
    - pytest-mock>=1.10
    - pytest-env>=0.6.2
    - moto
    - check-manifest
    - black; python_version >= '3.6'
    - attrs>=17.4.0
    - pre-commit
    - boto3
    - botocore
    - ipywidgets
    - flake8
    - tox
    - bumpversion
    - pip>=18.1
    - wheel>=0.31.0
    - setuptools>=38.6.0
    - twine>=1.11.0
    - google_compute_engine
  imports:
    - papermill

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Papermill is a tool for parameterizing, executing, and analyzing Jupyter Notebooks."
  doc_url: http://papermill.readthedocs.io/en/latest/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
