package:
  name: "papermill"
  version: "0.19.0"

source:
  url: https://pypi.org/project/papermill-0.19.0.tar.gz
  sha256: d62d7edcb635040a84ccf42b6dcc7e9163a8945059c8eee5211218f56d8f3904

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - papermill
    - papermill.tests
  requires:
    - pytest
  commands:
    - py.test --pyargs papermill

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Papermill is a tool for parameterizing, executing, and analyzing Jupyter Notebooks."
  doc_url: http://papermill.readthedocs.io/en/latest/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
