{% set name = "papermill" %}
{% set version = "2.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/nteract/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ec3d6ae68e56c1824497bb0155f97297842bd26e27e33df2eb62ddb1f67a021d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation
  entry_points:
    - papermill = papermill.cli:papermill
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=61
    - wheel
  run:
    - python
    - ansicolors
    - aiohttp >=3.9.0 # [py==312]
    - click
    - entrypoints
    - nbclient >=0.2.0
    - nbformat >=5.2.0
    - pyyaml
    - requests
    - tenacity >=5.0.2
    - tqdm >=4.32.2
  run_constrained:
    - azure-datalake-store >=0.0.30,<1
    - azure-identity >=1.3.1
    - azure-storage-blob >=12.1
    - black >=19.3b0
    - gcsfs >=0.2
    - pyarrow >=2
    - pygithub >=1.55
    - requests >=2.21

# No azure-identity <1 in main channel:
{% set ignore_tests = " --ignore=papermill/tests/test_abs.py" %}
# No azure-datalake-store <1 in main channel:
{% set ignore_tests = ignore_tests + " --ignore=papermill/tests/test_adl.py" %}

# Unstable tests: Exception: {'message': 'test', 'code': 429} - raise_limit_exception
{% set deselect_tests = " --deselect=papermill/tests/test_gcs.py::GCSTest::test_gcs_fallback_retry_unknown_failure_code" %}
{% set deselect_tests = deselect_tests + " --deselect=papermill/tests/test_gcs.py::GCSTest::test_gcs_handle_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=papermill/tests/test_gcs.py::GCSTest::test_gcs_retry" %}
{% set deselect_tests = deselect_tests + " --deselect=papermill/tests/test_gcs.py::GCSTest::test_gcs_retry_older_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=papermill/tests/test_hdfs.py::HDFSTest::test_hdfs_listdir" %}
{% set deselect_tests = deselect_tests + " --deselect=papermill/tests/test_autosave.py::TestMidCellAutosave::test_end2end_autosave_slow_notebook" %}

test:
  source_files:
    - papermill
  imports:
    - papermill
  commands:
    - pip check
    - papermill --help
    # Unable to run with --pyargs, skip py314 unable to configure tests - missing deps.
    - python -m pytest papermill/tests {{ ignore_tests }} {{ deselect_tests }}  # [py<314]
  requires:
    - boto3
    - moto >=5,<5.1  # [py<314]
    - aiohttp
    - pip
    - pytest
    - ansicolors
    - azure-storage-blob >=12.1
    - requests >=2.21
    - matplotlib-base
    - ipywidgets
    - ipykernel
    - ipython >=5,<9  # [py<314]
    - notebook

about:
  home: https://github.com/nteract/papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks.
  description: |
    Papermill is a tool for parameterizing and executing Jupyter Notebooks.
    Papermill lets you parameterize notebooks and execute notebooks
  doc_url: https://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
