{% set name = "papermill" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nteract/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ddfd94093ce26e68b10c9546f596293e9bf7e13e2977ae7d4f0a8a3bd92ac95f
  patches:
    - 0001_fix_test.patch

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - ansicolors
    - aiohttp >=3.9.0 # [py312]
    - click
    - entrypoints
    - nbclient >=0.2.0
    - nbformat >=5.2.0
    - python
    - pyyaml
    - requests
    - tenacity >=5.0.2
    - tqdm >=4.32.2


# Skip these tests because next packages are unavailable now in conda:     
# - gcsfs>=0.2.0
# - azure-datalake-store >= 0.0.30
# - azure-identity>=1.3.1
{% set ignore_tests = [
  "--ignore=papermill/tests/test_abs.py",
  "--ignore=papermill/tests/test_adl.py",
  "--ignore=papermill/tests/test_gcs.py"
] %}

{% set ignore_tests_cases = [
  # Jupyter required. but is incompatible with current packages
  "test_output_formatting",
  "TestBrokenNotebook2"
] %}

test:
  source_files:
    - pyproject.toml
    - pytest.ini
    - papermill
  imports:
    - papermill
  requires:
    - boto3
    - moto >= 5.0.0,<5.1.0
    - pip
    - pytest
    - ansicolors
    - azure-storage-blob >= 12.1.0
    - requests >= 2.21.0
    - matplotlib
    - ipywidgets
    - ipykernel
    - ipython>=5.0
    - notebook
  commands:
    - papermill --help
    - pip check
    - python -m pytest papermill/tests {{ ignore_tests | join(' ') }} -k "not ({{ ignore_tests_cases | join(' or ') }})"

about:
  home: https://github.com/nteract/papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks.
  description: |
    Papermill is a tool for parameterizing and executing Jupyter Notebooks.
    Papermill lets you parameterize notebooks and execute notebooks
  doc_url: https://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
