{% set name = "papermill" %}
{% set version = "0.19.1" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c08c1ce99fab7ec797187db54c49a7dcb3ed596816e757e99fa2a8c472ff39c

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - ansiwrap
    - backports.tempfile
    - click
    - entrypoints
    - future
    - futures
    - ipython >=5.0
    - jupyter_client
    - nbconvert >=5.4
    - nbformat
    - pandas
    - python
    - pyyaml
    - requests
    - six
    - tenacity
    - tqdm >=4.29.1
    - pip

test:
  requires:
    - ansiwrap
    - backports.tempfile
    - click
    - entrypoints
    - future
    - futures
    - ipython >=5.0
    - jupyter_client
    - nbconvert >=5.4
    - nbformat
    - pandas
    - python
    - pyyaml
    - requests
    - six
    - tqdm >=4.29.1
    - tenacity
    - pip
  imports:
    - papermill
  commands:
    - python -c "import papermill"

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: "BSD"
  license_file: LICENSE
  summary: "Papermill parameterizes, executes, and analyzes Jupyter Notebooks."
  doc_url: http://papermill.readthedocs.io/en/latest/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
