{% set name = "papermill" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c08c1ce99fab7ec797187db54c49a7dcb3ed596816e757e99fa2a8c472ff39c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - papermill

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Papermill parameterizes, executes, and analyzes Jupyter Notebooks."
  doc_url: http://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
