{% set name = "papermill" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecd4cafa9179693b0eedc3b6f4560f9ee47826a6e366e42bfa3cc20f7931b3f8

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: true  # [py<35, python_impl == 'pypy']

requirements:
  host:
    - python
    - pip
    - setuptools
    - ansiwrap
    - click
    - entrypoints
    - jupyter_client
    - nbclient >=0.2.0
    - nbformat
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2
    - black
  run:
    - python
    - pip
    - ansiwrap
    - click
    - entrypoints
    - jupyter_client
    - nbclient >=0.2.0
    - nbformat
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2
    - black

test:
  imports:
    - papermill
  commands:
    - papermill --help

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks.
  doc_url: http://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
