travis:
  secure:
    BINSTAR_TOKEN: G7GbS9InHho9C8pmHLOP3YLNM1lu+DxrXhRZTKi44tjns8uHXyw6KV0nrEb3k2w2dEnKqs5T6mLBUytl+osQn9UPUmiE4duAYYlLyFPP50sbBvZdpxN4WXyjWzA/Al1nPs4I2axP6kzBzWAmHv1M6magiuup+9j7e+us60rTf9DOmhezcaN/nnShksmyO8KDb1u+Du9TR6BgS3JqkqsFQ9BUeLKlMWhM8aB/nEwdiJ1cPNScKFMbNZof/dnEiEd0BmpQe0HLwPm73mk/ppbI8IdpBvUvojey+wr96305ZEUKCqpXaVhW0WNSgeKhXtqziyXcxlpzl4mJiT6dSx694vHcz96A3qNLrgqc8VjTF4Jcl+UJeJAiZ3SlXblhnWOmJs5gzCtANwim2ZrTOxcBOhp1wiBSpnggwOukfmsM699vMA5a/ktz4Pe96CvKeTffyCTcM3S0Nb3yqm3fbGAshAaul/nxYq977Qh9weorv2cSXM40vcCDrBfWLCwdIHKS3xl7Y34M/KExk69SbyCWFOpE7NuFHeBB03Pr72KINVAYM+xYLW6F3EXDEV0XTcj0n1I1/3WYzbtS8SXKgOKQcqQeJPFhhu+grfJGf7EmZbbm58rxiyLOF2klyUjs3eLTP2U/ND7dLS/8rj1Vi6qTBa9IDYQl1PdB+H0GHFwvbxY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
